# Generated by Django 4.2.3 on 2023-07-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.seller_info'),
        ),
    ]
