# Generated by Django 4.2.3 on 2023-07-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_seller_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_info'),
        ),
    ]
