# Generated by Django 4.2.3 on 2023-07-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('payment', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.seller_info'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('finished', 'Finished')], default='created', max_length=20),
        ),
    ]
