# Generated by Django 4.2.3 on 2023-07-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_info',
        ),
    ]
