# Generated by Django 4.2.3 on 2023-07-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_order_seller_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
